[core]
reloadable = true


[package]
# Semantic Versioning is used: https://semver.org/
version = "0.0.5"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Emanuel Kozerski"]

# The title and description fields are primarily for displaying extension info in UI
title = "RTX Remix Tools"
description="Simple toolkit for creating remixing assets compatible with RTX Remix runtime"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/Ekozmaster/Nvidia-Omniverse-RTX-Remix-Tools"

# One of categories for UI.
category = "Other"

# Keywords for the extension
keywords = ["Tool", "Toolkit", "Tools", "RTX", "Remix"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}


# Main python module this extension provides, it will be publicly available as "import ekozerski.rtxremixtools".
[[python.module]]
name = "ekozerski.rtxremixtools"


[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]
